INSERT OR IGNORE INTO agentsam_commands
(id, command_key, command_name, command_category, description, prompt_template, allowed_roles, allowed_modes, provider_strategy, default_model, safety_level, sort_order)
VALUES
('cmd_social_caption', 'social.caption.generate', 'Generate Social Caption', 'social',
 'Generate approved Facebook/Instagram/YouTube-ready post copy for rescue updates.',
 'Create a clear, warm, nonprofit-safe social post for: {{context}}',
 '["owner","developer","admin","volunteer"]',
 '["ask","agent"]',
 'auto',
 'workers-ai-llama-3.1-8b',
 'standard',
 10),

('cmd_donor_email', 'email.donor.thank_you', 'Generate Donor Thank You Email', 'email',
 'Draft donor thank-you emails using approved rescue tone.',
 'Write a donor thank-you email for {{donor_name}} after a donation of {{amount}}.',
 '["owner","developer","admin"]',
 '["ask","agent"]',
 'auto',
 'workers-ai-llama-3.1-8b',
 'standard',
 20),

('cmd_event_campaign', 'fundraising.event.campaign', 'Generate Fundraising Campaign', 'fundraising',
 'Generate campaign copy for donations, events, and rescue fundraising drives.',
 'Create a fundraising campaign for {{event_title}} with goal {{goal}}.',
 '["owner","developer","admin"]',
 '["plan","agent"]',
 'auto',
 'workers-ai-llama-3.1-8b',
 'standard',
 30),

('cmd_dashboard_summary', 'dashboard.summary.generate', 'Generate Dashboard Summary', 'operations',
 'Summarize donations, applications, contact requests, and animal status.',
 'Summarize the current dashboard data for board members: {{data}}',
 '["owner","developer","admin"]',
 '["ask","plan"]',
 'auto',
 'local-llama',
 'standard',
 40);

INSERT OR IGNORE INTO agentsam_mcp_tools
(id, tool_key, tool_name, display_name, tool_category, description, input_schema, output_schema, intent_tags, modes_json, handler_type, handler_config, provider, requires_auth, requires_secret_keys, safety_level, sort_order)
VALUES
('tool_wrangler_deploy', 'wrangler.deploy', 'wrangler.deploy', 'Wrangler Deploy', 'cloudflare',
 'Deploy the Companions CPAS Worker and Static Assets through Wrangler.',
 '{"type":"object","properties":{"environment":{"type":"string"},"dry_run":{"type":"boolean"}}}',
 '{"type":"object","properties":{"success":{"type":"boolean"},"deployment_url":{"type":"string"},"version_id":{"type":"string"}}}',
 '["cloudflare","worker","deploy","wrangler"]',
 '["agent","debug"]',
 'cli',
 '{"command":"npx wrangler deploy","requires_local_shell":true}',
 'cloudflare',
 1,
 '["CLOUDFLARE_API_TOKEN","CLOUDFLARE_ACCOUNT_ID"]',
 'elevated',
 10),

('tool_wrangler_d1', 'wrangler.d1.execute', 'wrangler.d1.execute', 'Wrangler D1 Execute', 'cloudflare',
 'Execute SQL against the Companions CPAS D1 database.',
 '{"type":"object","properties":{"sql":{"type":"string"},"file":{"type":"string"},"remote":{"type":"boolean"}}}',
 '{"type":"object","properties":{"success":{"type":"boolean"},"rows":{"type":"array"}}}',
 '["cloudflare","d1","database","sql"]',
 '["agent","debug"]',
 'cli',
 '{"command":"npx wrangler d1 execute companionscpas --remote","database":"companionscpas","binding":"DB"}',
 'cloudflare',
 1,
 '["CLOUDFLARE_API_TOKEN","CLOUDFLARE_ACCOUNT_ID"]',
 'elevated',
 20),

('tool_resend_email', 'resend.email.send', 'resend.email.send', 'Send Email via Resend', 'email',
 'Send transactional or admin-approved emails through Resend.',
 '{"type":"object","properties":{"to":{"type":"string"},"subject":{"type":"string"},"html":{"type":"string"},"text":{"type":"string"}}}',
 '{"type":"object","properties":{"success":{"type":"boolean"},"provider_message_id":{"type":"string"}}}',
 '["email","resend","donor","contact","newsletter"]',
 '["agent"]',
 'http',
 '{"endpoint":"https://api.resend.com/emails","method":"POST"}',
 'resend',
 1,
 '["RESEND_API_KEY"]',
 'standard',
 30),

('tool_stripe_checkout', 'stripe.checkout.create', 'stripe.checkout.create', 'Create Stripe Checkout', 'payments',
 'Create a Stripe Checkout Session for one-time or recurring donations.',
 '{"type":"object","properties":{"amount_cents":{"type":"integer"},"donor_email":{"type":"string"},"recurring":{"type":"boolean"}}}',
 '{"type":"object","properties":{"checkout_url":{"type":"string"},"stripe_session_id":{"type":"string"}}}',
 '["stripe","donations","checkout","payments"]',
 '["agent"]',
 'http',
 '{"endpoint":"https://api.stripe.com/v1/checkout/sessions","method":"POST"}',
 'stripe',
 1,
 '["STRIPE_SECRET_KEY"]',
 'elevated',
 40),

('tool_workers_ai', 'workersai.run', 'workersai.run', 'Workers AI Run', 'ai',
 'Run lightweight AI tasks through Cloudflare Workers AI.',
 '{"type":"object","properties":{"model":{"type":"string"},"prompt":{"type":"string"},"max_tokens":{"type":"integer"}}}',
 '{"type":"object","properties":{"reply":{"type":"string"},"tokens":{"type":"integer"}}}',
 '["ai","workers-ai","caption","summary"]',
 '["ask","agent"]',
 'binding',
 '{"binding":"AI","default_model":"@cf/meta/llama-3.1-8b-instruct"}',
 'cloudflare-workers-ai',
 0,
 '[]',
 'standard',
 50),

('tool_local_llama', 'local.llama.run', 'local.llama.run', 'Local Llama Run', 'ai',
 'Route prompts to local Llama/Ollama for low-cost local generation when available.',
 '{"type":"object","properties":{"endpoint":{"type":"string"},"model":{"type":"string"},"prompt":{"type":"string"}}}',
 '{"type":"object","properties":{"reply":{"type":"string"},"latency_ms":{"type":"integer"}}}',
 '["ai","local","llama","ollama","cheap"]',
 '["ask","plan","agent"]',
 'http',
 '{"endpoint":"http://localhost:11434/api/generate","default_model":"llama3.1"}',
 'local-llama',
 0,
 '[]',
 'standard',
 60);

INSERT OR IGNORE INTO agentsam_analytics
(id, tenant_id, provider, model_key, runtime_location, mode, status, metadata_json, started_at, completed_at)
VALUES
('analytics_bootstrap_agentsam_001', 'tenant_companionscpas', 'system', 'bootstrap', 'd1', 'setup', 'completed',
 '{"note":"Agent Sam analytics table initialized for command/tool/provider tracking."}',
 datetime('now'), datetime('now'));
